//HintName: GitInfo.g.cs
// <auto-generated />

// cacheHit: False
// gitInformationRead: 2023-11-18 00:01:02Z

#nullable enable

using System;

namespace ApplicationNamespace;

public static class GitInfo
{
    public const string Branch = "main";

    public const string CommitAbbreviatedHash = "eb36715d2";

    public const string CommitHash = "eb36715d2707630f4267d65da0f8a6037b2fd3fe";

    public static DateTimeOffset CommitDate = new DateTimeOffset(638359305790000000, new TimeSpan(36000000000));

    public static string? TagName = "0.1.1";

    public static string? Tag = "0.1.1";

    public static int? TagMajor = 0;

    public static int? TagMinor = 1;

    public static int? TagBuild = 1;

    public static int? TagRevision = null;
}

#nullable restore
