//HintName: GitInfo.g.cs
// <auto-generated />

// cacheHit: False
// gitInformationRead: 2023-11-18 00:01:02Z

#nullable enable

using System;

namespace ApplicationNamespace;

public static class GitInfo
{
    public const string Branch = "main";

    public const string CommitAbbreviatedHash = "cad7fcf55";

    public const string CommitHash = "cad7fcf5550eda59482ae34606b7ccb4ef09e720";

    public static DateTimeOffset CommitDate = new DateTimeOffset(638359305230000000, new TimeSpan(36000000000));

    public static string? TagName = null;

    public static string? Tag = null;

    public static int? TagMajor = null;

    public static int? TagMinor = null;

    public static int? TagBuild = null;

    public static int? TagRevision = null;
}

#nullable restore
