//HintName: GitInfo.g.cs
// <auto-generated />

// cacheHit: False
// gitInformationRead: 2023-11-18 00:01:02Z

#nullable enable

using System;

namespace ApplicationNamespace;

public static class GitInfo
{
    public const string Branch = "main";

    public const string CommitAbbreviatedHash = "41f85d012";

    public const string CommitHash = "41f85d012eb9b71eadb3a7ba68f9bfa840e8bd8a";

    public static DateTimeOffset CommitDate = new DateTimeOffset(638359270600000000, new TimeSpan(36000000000));

    public static string? TagName = "v0.1.0";

    public static string? Tag = "v0.1.0";

    public static int? TagMajor = 0;

    public static int? TagMinor = 1;

    public static int? TagBuild = 0;

    public static int? TagRevision = null;
}

#nullable restore
